nome = str(input('Qual é o seu nome? '))
print(f'\nPrazer em te conhecer, {nome:20}!')
print(f'\nPrazer em te conhecer, {nome:>20}!')
print(f'\nPrazer em te conhecer, {nome:^20}!')
print(f'\nPrazer em te conhecer, {nome:=^20}!')
